services:
  backend:
    image: ai-media2doc-backend:latest
    env_file:
      - "variables.env"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8080:8080"

  frontend:
    image: ai-media2doc-frontend:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5173:5173"
